
name: abu_bahri_tasks
description: جدول أبو بحري - Daily Planner from Fajr to 12AM
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  adhan: ^2.0.0
  geolocator: ^10.1.0
  flutter_qiblah: ^2.2.1
  geocoding: ^2.1.1
  just_audio: ^0.9.36
  flutter_tts: ^4.0.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/quran/
